# Generated by Django 5.2.5 on 2025-08-22 10:38

from django.db import migrations, models


def generate_order_numbers(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    for i, order in enumerate(Order.objects.all()):
        order.order_number = str(1000 + i)
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_payment_method_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(generate_order_numbers),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
