"""
Django settings for shivdairy project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(Path(__file__).resolve().parent.parent / '.env')
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS configuration
# Support both development and production domains
env_hosts = os.environ.get('ALLOWED_HOSTS', '')
if env_hosts:
    # Parse comma-separated hosts from environment
    ALLOWED_HOSTS = [host.strip() for host in env_hosts.split(',') if host.strip()]
else:
    # Default hosts: development + production domain
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'shivorganicdairyfarms.com',
        'www.shivorganicdairyfarms.com',
        '*.onrender.com',  # Keep for Render deployment
        'shiv-dairy-website.onrender.com',  # Old Render URL (backward compatibility)
    ]

# Debug logging
print(f"[CONFIG] ALLOWED_HOSTS = {ALLOWED_HOSTS}")
print(f"[CONFIG] DEBUG mode = {DEBUG}")

# Production Security Settings
if not DEBUG:
    # SECURE_SSL_REDIRECT = True  # Commented out for Render compatibility
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = False  # Changed for Render compatibility
    CSRF_COOKIE_SECURE = False     # Changed for Render compatibility
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this line
    'store.middleware.AllowAllHostsMiddleware',  # Custom middleware to allow all hosts
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shivdairy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shivdairy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,
            }
        }
    }
else:
    # Production: Use PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = []

# Static file serving with WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Email providers - Brevo (simplest) or SendGrid
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '').strip()  # Recommended: Simple API, 300 emails/day free
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '').strip()  # Alternative: SendGrid API
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'shivorganicdairyfarms@gmail.com')
EMAIL_FROM_NAME = os.environ.get('EMAIL_FROM_NAME', 'Shiv Organic Dairy Farms')

# Debug email configuration at startup
if BREVO_API_KEY:
    print(f"[EMAIL] Brevo API key configured (length: {len(BREVO_API_KEY)})")
else:
    print(f"[EMAIL] Brevo API key NOT configured")
if SENDGRID_API_KEY:
    print(f"[EMAIL] SendGrid API key configured")
ORDER_NOTIFICATION_EMAIL = os.environ.get('ORDER_NOTIFICATION_EMAIL', 'shivorganicdairyfarms@gmail.com')
COMPANY_WHATSAPP_PHONE = os.environ.get('COMPANY_WHATSAPP_PHONE', '')  # Company WhatsApp number for order notifications

# Email configuration - SMTP settings (Gmail or Brevo SMTP)
# Default to Gmail SMTP for reliable general SMTP
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')  # Default to Gmail
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'shivorganicdairyfarms@gmail.com')
EMAIL_HOST_PASSWORD_RAW = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD_RAW.replace(' ', '') if EMAIL_HOST_PASSWORD_RAW else ''
EMAIL_TIMEOUT = 30  # Increased from 5 to 30 seconds for better reliability
EMAIL_USE_SSL = False  # Use TLS, not SSL

# Always set SMTP as the backend to ensure it works
# The views.py will try API methods first, then fall back to SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Debug email configuration
print(f"[SMTP] Configuration:")
print(f"   Host: {EMAIL_HOST}")
print(f"   Port: {EMAIL_PORT}")
print(f"   User: {EMAIL_HOST_USER}")
print(f"   Password configured: {'Yes' if EMAIL_HOST_PASSWORD else 'No'}")
print(f"   Password length: {len(EMAIL_HOST_PASSWORD)} chars")
print(f"   Use TLS: {EMAIL_USE_TLS}")
print(f"   Timeout: {EMAIL_TIMEOUT}s")

if not EMAIL_HOST_PASSWORD:
    print(f"[WARNING] EMAIL_HOST_PASSWORD not set! SMTP will fail.")
    print(f"   Set EMAIL_HOST_PASSWORD environment variable with your Gmail App Password")
    print(f"   Or configure Brevo/SendGrid API keys for alternative email methods")
else:
    print(f"[OK] SMTP email backend ready")

# WhatsApp Cloud API (Meta/Facebook) - 1,000 free messages/month
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '').strip()
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '').strip()
WHATSAPP_API_VERSION = os.environ.get('WHATSAPP_API_VERSION', 'v18.0').strip()

# Debug WhatsApp configuration
if WHATSAPP_ACCESS_TOKEN:
    print(f"[WHATSAPP] Meta WhatsApp Cloud API configured")
    print(f"   Phone Number ID: {WHATSAPP_PHONE_NUMBER_ID if WHATSAPP_PHONE_NUMBER_ID else 'Not set'}")
    print(f"   API Version: {WHATSAPP_API_VERSION}")
else:
    print(f"[WHATSAPP] Meta WhatsApp Cloud API NOT configured")
    print(f"   Set WHATSAPP_ACCESS_TOKEN and WHATSAPP_PHONE_NUMBER_ID environment variables")
    print(f"   Get them from: https://business.facebook.com/")

# Razorpay Configuration
# For production - using real keys from environment variables
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', 'rzp_live_your_actual_key_id')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', 'your_actual_secret_key')

# For production, set these environment variables:
# RAZORPAY_KEY_ID=rzp_live_your_actual_key_id
# RAZORPAY_KEY_SECRET=your_actual_secret_key

# Note: For production, get your actual keys from: https://dashboard.razorpay.com/app/keys
# Set these environment variables:
# RAZORPAY_KEY_ID=your_actual_key_id
# RAZORPAY_KEY_SECRET=your_actual_secret_key

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
